version: "3.7"

services:
  redis:
    container_name: workout-redis
    image: redis
    command: redis-server --port 6379
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"

  nginx:
    container_name: workout-nginx
    build:
      context: ./infrastructure/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"

  backend:
    container_name: workout-backend
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis

  prometheus:
    container_name: workout-prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  grafana:
    container_name: workout-grafana
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./infrastructure/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
